/**
 * Re-export all Prisma generated types
 *
 * This file provides a centralized location to import all
 * database types generated by Prisma.
 *
 * @packageDocumentation
 */

export * from '@prisma/client';

// Re-export specific types for convenience
export type {
  Contact,
  Property,
  Building,
  Request,
  Match,
  Activity,
  Tag,
  EntityTag,
  UserProfile,
  AuditLog,
  CustomFieldDefinition,
  CustomFieldValue,
  ScrapingJob,
  ScrapingSession,
  ScrapingSource,
  AgentConversation,
  AgentTask,
  AgentMemory,
  IntegrationAuth,
  MessageLog,
  CalendarSync,
  MessageProcessing,
  ContactStatus,
  PropertyStatus,
  RequestStatus,
  MatchStatus,
  ActivityStatus,
  Prisma,
} from '@prisma/client';
